DROP TABLE IF EXISTS "QUOTE";

CREATE TABLE QUOTE (
    ID IDENTITY NOT NULL PRIMARY KEY,
    TEXT VARCHAR(255) NOT NULL,
    UPD DATE NOT NULL,
    USERID INT NOT NULL,
    SCORE INT NOT NULL
);

DROP TABLE IF EXISTS "MYUSER";

CREATE TABLE "MYUSER" (
    ID IDENTITY NOT NULL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(50) NOT NULL,
    REG_DATE DATE NOT NULL
);

DROP TABLE IF EXISTS "VOTE";

CREATE TABLE VOTE (
    ID IDENTITY NOT NULL PRIMARY KEY,
    USERID INT NOT NULL,
    QUOTEID INT NOT NULL,
    VOTEDATE DATE NOT NULL,
    ISUP BOOLEAN NOT NULL
);

